### ISSUE TITLE
Create newline on `Enter` from mobile

### ISSUE THREAD

**Issue by KaKi87** [mat-1/variance#2]
### Describe the problem

Pressing `Enter` on mobile sends a message, preventing the user from creating a newline.

### Describe the solution you'd like

Pressing `Enter` on mobile would create a newline, and only the *send* button would send a message.

### Alternatives considered

None

### Additional context

The requested behavior is the same as Discord.
Also, like on Discord, `Enter` would still send a message on desktop, while `Ctrl-Enter` would create a newline.

---
Thanks

**Comment by mat-1** [comment]
This is implemented as the "send message on enter" setting in accessibility settings, but it does have to be disabled manually which isn't super intuitive. I'll leave this issue open since it would be cool if it automatically detected if you're using a mobile keyboard.

**Comment by KaKi87** [comment]
Here's a way to do that :
```js
/** @type {boolean} - Whether the device has a touch screen */
const isTouchScreen = window.matchMedia('(hover: none)').matches;
```
Thanks
