### ISSUE TITLE
URL previews are rendered even for pillified/linkified room names, and in code-formatted text

### ISSUE THREAD

**Issue by williamkray** [mat-1/variance#6]
### Describe the bug

if url previews are enabled, they are rendered when full room IDs are used (e.g. references to #roomname:homeserver.tld would render a url preview for homeserver.tld). they are also rendered even if the text is wrapped in codeblocks or inline code. this is unexpected behavior in both cases.

### Reproduction

1. enable url previews in variance settings.
2. send a message in any room from any client that includes:
    a.  a room address
    b. a room alias
    c. a room ID
    d. a full matrix ID (i.e. not a pillified matrix.to link)
4. view the message in variance. note the url preview generated below each message.

![image](https://github.com/mat-1/variance/assets/8409433/26324bf1-4e61-4428-9c96-1c94f6f4d381)

### Expected behavior

this message should not generate a url preview because it is never intended to be a link to a website.

### Platform and versions

```shell
arch linux, firefox, https://variance.matdoes.dev as of the date of this posting
```

**Comment by williamkray** [comment]
i think code-formatted text is actually:

- only for multiline codeblocks, and
- an upstream issue

**Comment by mat-1** [comment]
thanks for reporting, i went ahead and improved a bunch of stuff related to how url previews look while fixing this issue so they should be much more usable now
