### ISSUE TITLE
chat address is not working

### ISSUE THREAD

**Issue by williamkray** [mat-1/variance#8]
### Describe the bug

have been trying to join [#variance:matdoes.dev](https://matrix.to/#/#variance:matdoes.dev) for two days and get the following error:
![Screenshot_20240401100407](https://github.com/mat-1/variance/assets/8409433/e62425a0-db46-4ca4-933b-70c7ab0bbfea)

### Platform and versions

```shell
tested on cinny and element web.
```

**Comment by mat-1** [comment]
The Variance Matrix room isn't used anymore because Variance is currently not being actively maintained.
